aws:
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  region: us-east-1
  sns:
    topic:
      catalog:
        arn: arn:aws:sns:us-east-1:000000000000:catalog-prod
server:
  port: 8080
